# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-20 16:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iotdb_link', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datafromdevice',
            name='parking_slot',
        ),
    ]
