# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-20 16:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iotdb_link', '0002_remove_datafromdevice_parking_slot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='parking_slot',
            field=models.IntegerField(),
        ),
    ]
