# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-18 13:41
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Common',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resourceID', models.CharField(blank=True, max_length=200)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('accessControlPolicyIDs', models.CharField(blank=True, max_length=200)),
                ('creationTime', models.DateTimeField(blank=True, null=True)),
                ('lastModifiedTime', models.DateTimeField(blank=True, null=True)),
                ('expirationTime', models.DateTimeField(default=datetime.datetime(2099, 11, 16, 0, 0))),
                ('labels', models.CharField(blank=True, max_length=200)),
                ('announceTo', models.CharField(blank=True, max_length=200)),
                ('announcedAttribute', models.CharField(blank=True, max_length=200)),
                ('dynamicAuthorizationConsultationIDs', models.CharField(blank=True, max_length=200)),
                ('lft', models.PositiveIntegerField(db_index=True, editable=False)),
                ('rght', models.PositiveIntegerField(db_index=True, editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(db_index=True, editable=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(default=5, max_length=2)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('lft', models.PositiveIntegerField(db_index=True, editable=False)),
                ('rght', models.PositiveIntegerField(db_index=True, editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(db_index=True, editable=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='APP',
            fields=[
                ('common_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='resources.Common')),
                ('resourceType', models.IntegerField(default=2)),
                ('appName', models.CharField(blank=True, max_length=200)),
                ('App_ID', models.CharField(blank=True, max_length=200)),
                ('AE_ID', models.CharField(blank=True, max_length=200)),
                ('pointOfAccess', models.CharField(blank=True, max_length=200)),
                ('nodeLink', models.CharField(blank=True, max_length=200)),
                ('contentSerialization', models.CharField(blank=True, max_length=200)),
                ('requestReachability', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('resources.common',),
        ),
        migrations.CreateModel(
            name='CONTAINER',
            fields=[
                ('common_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='resources.Common')),
                ('resourceType', models.IntegerField(default=3)),
            ],
            options={
                'abstract': False,
            },
            bases=('resources.common',),
        ),
        migrations.CreateModel(
            name='CONTENTINSTANCE',
            fields=[
                ('common_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='resources.Common')),
                ('resourceType', models.IntegerField(default=4)),
                ('content', models.CharField(max_length=1000)),
            ],
            options={
                'abstract': False,
            },
            bases=('resources.common',),
        ),
        migrations.CreateModel(
            name='CSE',
            fields=[
                ('common_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='resources.Common')),
                ('resourceType', models.IntegerField(default=5)),
                ('CSE_ID', models.CharField(default='InCSE1', max_length=200)),
                ('CSE_Type', models.CharField(default='IN-CSE', max_length=200)),
                ('supportedResourceType', models.CharField(blank=True, max_length=200)),
                ('pointOfAccess', models.CharField(blank=True, max_length=200)),
                ('nodeLink', models.CharField(blank=True, max_length=200)),
                ('e2eSecInfo', models.CharField(blank=True, max_length=200)),
                ('notificationCongestionPolicy', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'abstract': False,
            },
            bases=('resources.common',),
        ),
        migrations.CreateModel(
            name='SUBSCRIPTION',
            fields=[
                ('common_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='resources.Common')),
                ('resourceType', models.IntegerField(default=23)),
                ('notificationURI', models.CharField(default='http://localhost:8586', max_length=2000)),
                ('notificationContentType', models.IntegerField(default=1)),
                ('eventNotificationCriteria', models.CharField(default='{"net":[6]', max_length=100)),
            ],
            options={
                'abstract': False,
            },
            bases=('resources.common',),
        ),
        migrations.CreateModel(
            name='test1',
            fields=[
                ('test_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='resources.test')),
                ('test1_field', models.CharField(default='default test 1', max_length=10)),
            ],
            options={
                'abstract': False,
            },
            bases=('resources.test',),
        ),
        migrations.CreateModel(
            name='test2',
            fields=[
                ('test_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='resources.test')),
                ('test2_field', models.CharField(default='default test 2', max_length=10)),
            ],
            options={
                'abstract': False,
            },
            bases=('resources.test',),
        ),
        migrations.AddField(
            model_name='test',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='resources.test'),
        ),
        migrations.AddField(
            model_name='common',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='resources.Common'),
        ),
        migrations.CreateModel(
            name='TREE',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('resources.common',),
        ),
    ]
