# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-20 07:44
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
import polymorphic_tree.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resourceID', models.CharField(blank=True, max_length=200)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('accessControlPolicyIDs', models.CharField(blank=True, max_length=200)),
                ('creationTime', models.DateTimeField(blank=True, null=True)),
                ('lastModifiedTime', models.DateTimeField(blank=True, null=True)),
                ('expirationTime', models.DateTimeField(default=datetime.datetime(2099, 11, 16, 0, 0))),
                ('labels', models.CharField(blank=True, max_length=200)),
                ('announceTo', models.CharField(blank=True, max_length=200)),
                ('announcedAttribute', models.CharField(blank=True, max_length=200)),
                ('dynamicAuthorizationConsultationIDs', models.CharField(blank=True, max_length=200)),
                ('lft', models.PositiveIntegerField(db_index=True, editable=False)),
                ('rght', models.PositiveIntegerField(db_index=True, editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(db_index=True, editable=False)),
            ],
            options={
                'ordering': ('tree_id', 'lft'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('lft', models.PositiveIntegerField(db_index=True, editable=False)),
                ('rght', models.PositiveIntegerField(db_index=True, editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(db_index=True, editable=False)),
            ],
            options={
                'ordering': ('tree_id', 'lft'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='APP',
            fields=[
                ('resource_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='resources.Resource')),
                ('resourceType', models.IntegerField(default=2)),
                ('appName', models.CharField(blank=True, max_length=200)),
                ('App_ID', models.CharField(blank=True, max_length=200)),
                ('AE_ID', models.CharField(blank=True, max_length=200)),
                ('pointOfAccess', models.CharField(blank=True, max_length=200)),
                ('nodeLink', models.CharField(blank=True, max_length=200)),
                ('contentSerialization', models.CharField(blank=True, max_length=200)),
                ('requestReachability', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('tree_id', 'lft'),
                'abstract': False,
            },
            bases=('resources.resource',),
        ),
        migrations.CreateModel(
            name='CONTAINER',
            fields=[
                ('resource_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='resources.Resource')),
                ('resourceType', models.IntegerField(default=3)),
            ],
            options={
                'ordering': ('tree_id', 'lft'),
                'abstract': False,
            },
            bases=('resources.resource',),
        ),
        migrations.CreateModel(
            name='CONTENTINSTANCE',
            fields=[
                ('resource_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='resources.Resource')),
                ('resourceType', models.IntegerField(default=4)),
                ('content', models.CharField(max_length=1000)),
            ],
            options={
                'ordering': ('tree_id', 'lft'),
                'abstract': False,
            },
            bases=('resources.resource',),
        ),
        migrations.CreateModel(
            name='CSE',
            fields=[
                ('resource_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='resources.Resource')),
                ('resourceType', models.IntegerField(default=5)),
                ('CSE_ID', models.CharField(default='InCSE1', max_length=200)),
                ('CSE_Type', models.CharField(default='IN-CSE', max_length=200)),
                ('supportedResourceType', models.CharField(blank=True, max_length=200)),
                ('pointOfAccess', models.CharField(blank=True, max_length=200)),
                ('nodeLink', models.CharField(blank=True, max_length=200)),
                ('e2eSecInfo', models.CharField(blank=True, max_length=200)),
                ('notificationCongestionPolicy', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'ordering': ('tree_id', 'lft'),
                'abstract': False,
            },
            bases=('resources.resource',),
        ),
        migrations.CreateModel(
            name='SUBSCRIPTION',
            fields=[
                ('resource_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='resources.Resource')),
                ('resourceType', models.IntegerField(default=23)),
                ('notificationURI', models.CharField(default='http://localhost:8586', max_length=2000)),
                ('notificationContentType', models.IntegerField(default=1)),
                ('eventNotificationCriteria', models.CharField(default='{"net":[6]', max_length=100)),
            ],
            options={
                'ordering': ('tree_id', 'lft'),
                'abstract': False,
            },
            bases=('resources.resource',),
        ),
        migrations.CreateModel(
            name='test1',
            fields=[
                ('tes1_to_parent', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='resources.test')),
                ('test1_field', models.CharField(default='default test 1', max_length=10)),
            ],
            options={
                'ordering': ('tree_id', 'lft'),
                'abstract': False,
            },
            bases=('resources.test',),
        ),
        migrations.CreateModel(
            name='test2',
            fields=[
                ('tes2_to_parent', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='resources.test')),
                ('test2_field', models.CharField(default='default test 2', max_length=10)),
            ],
            options={
                'ordering': ('tree_id', 'lft'),
                'abstract': False,
            },
            bases=('resources.test',),
        ),
        migrations.AddField(
            model_name='test',
            name='parent',
            field=polymorphic_tree.models.PolymorphicTreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='resources.test'),
        ),
        migrations.AddField(
            model_name='test',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_resources.test_set+', to='contenttypes.ContentType'),
        ),
        migrations.AddField(
            model_name='resource',
            name='parent',
            field=polymorphic_tree.models.PolymorphicTreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='resources.Resource'),
        ),
        migrations.AddField(
            model_name='resource',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_resources.resource_set+', to='contenttypes.ContentType'),
        ),
    ]
