# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-05 19:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='APP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resourceID', models.CharField(blank=True, max_length=200)),
                ('resourceName', models.CharField(max_length=200)),
                ('parentID', models.CharField(max_length=200)),
                ('accessControlPolicyIDs', models.CharField(blank=True, max_length=200)),
                ('labels', models.CharField(blank=True, max_length=200)),
                ('announceTo', models.CharField(blank=True, max_length=200)),
                ('announcedAttribute', models.CharField(blank=True, max_length=200)),
                ('dynamicAuthorizationConsultationIDs', models.CharField(blank=True, max_length=200)),
                ('appName', models.CharField(blank=True, max_length=200)),
                ('App_ID', models.CharField(blank=True, max_length=200)),
                ('AE_ID', models.CharField(blank=True, max_length=200)),
                ('pointOfAccess', models.CharField(blank=True, max_length=200)),
                ('nodeLink', models.CharField(blank=True, max_length=200)),
                ('contentSerialization', models.CharField(blank=True, max_length=200)),
                ('requestReachability', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CONTAINER',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resourceID', models.CharField(blank=True, max_length=200)),
                ('resourceName', models.CharField(max_length=200)),
                ('parentID', models.CharField(max_length=200)),
                ('accessControlPolicyIDs', models.CharField(blank=True, max_length=200)),
                ('labels', models.CharField(blank=True, max_length=200)),
                ('announceTo', models.CharField(blank=True, max_length=200)),
                ('announcedAttribute', models.CharField(blank=True, max_length=200)),
                ('dynamicAuthorizationConsultationIDs', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CONTENTINSTANCE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resourceID', models.CharField(blank=True, max_length=200)),
                ('resourceName', models.CharField(max_length=200)),
                ('parentID', models.CharField(max_length=200)),
                ('accessControlPolicyIDs', models.CharField(blank=True, max_length=200)),
                ('labels', models.CharField(blank=True, max_length=200)),
                ('announceTo', models.CharField(blank=True, max_length=200)),
                ('announcedAttribute', models.CharField(blank=True, max_length=200)),
                ('dynamicAuthorizationConsultationIDs', models.CharField(blank=True, max_length=200)),
                ('content', models.CharField(max_length=1000)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CSEBase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resourceID', models.CharField(blank=True, max_length=200)),
                ('resourceName', models.CharField(max_length=200)),
                ('parentID', models.CharField(max_length=200)),
                ('accessControlPolicyIDs', models.CharField(blank=True, max_length=200)),
                ('labels', models.CharField(blank=True, max_length=200)),
                ('announceTo', models.CharField(blank=True, max_length=200)),
                ('announcedAttribute', models.CharField(blank=True, max_length=200)),
                ('dynamicAuthorizationConsultationIDs', models.CharField(blank=True, max_length=200)),
                ('CSE_ID', models.CharField(blank=True, max_length=200)),
                ('supportedResourceType', models.CharField(blank=True, max_length=200)),
                ('pointOfAccess', models.CharField(blank=True, max_length=200)),
                ('nodeLink', models.CharField(blank=True, max_length=200)),
                ('e2eSecInfo', models.CharField(blank=True, max_length=200)),
                ('notificationCongestionPolicy', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SUBSCRIPTION',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resourceID', models.CharField(blank=True, max_length=200)),
                ('resourceName', models.CharField(max_length=200)),
                ('parentID', models.CharField(max_length=200)),
                ('accessControlPolicyIDs', models.CharField(blank=True, max_length=200)),
                ('labels', models.CharField(blank=True, max_length=200)),
                ('announceTo', models.CharField(blank=True, max_length=200)),
                ('announcedAttribute', models.CharField(blank=True, max_length=200)),
                ('dynamicAuthorizationConsultationIDs', models.CharField(blank=True, max_length=200)),
                ('notificationURI', models.CharField(default='http://localhost:8586', max_length=2000)),
                ('notificationContentType', models.IntegerField(default=3)),
                ('eventNotificationCriteria', models.CharField(default='{"net":[6]}', max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
