# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-05 19:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='parent',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='resources.APP'),
        ),
        migrations.AddField(
            model_name='csebase',
            name='CSE_Type',
            field=models.CharField(default='IN-CSE', max_length=200),
        ),
        migrations.AlterField(
            model_name='csebase',
            name='CSE_ID',
            field=models.CharField(default='InCSE1', max_length=200),
        ),
    ]
