# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-05 19:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0002_auto_20161205_1941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='parent',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='resources.APP'),
        ),
    ]
