# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-05 19:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0003_auto_20161205_1948'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='app',
            name='parent',
        ),
    ]
