# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-08 07:14
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0004_remove_app_parent'),
    ]

    operations = [
        migrations.CreateModel(
            name='CSE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resourceID', models.CharField(blank=True, max_length=200)),
                ('resourceName', models.CharField(max_length=200)),
                ('parentID', models.CharField(max_length=200)),
                ('accessControlPolicyIDs', models.CharField(blank=True, max_length=200)),
                ('creationTime', models.DateTimeField(default=django.utils.timezone.now)),
                ('lastModifiedTime', models.DateTimeField(default=django.utils.timezone.now)),
                ('expirationTime', models.DateTimeField(default=datetime.datetime(2099, 11, 16, 0, 0))),
                ('labels', models.CharField(blank=True, max_length=200)),
                ('announceTo', models.CharField(blank=True, max_length=200)),
                ('announcedAttribute', models.CharField(blank=True, max_length=200)),
                ('dynamicAuthorizationConsultationIDs', models.CharField(blank=True, max_length=200)),
                ('CSE_ID', models.CharField(default='InCSE1', max_length=200)),
                ('CSE_Type', models.CharField(default='IN-CSE', max_length=200)),
                ('supportedResourceType', models.CharField(blank=True, max_length=200)),
                ('pointOfAccess', models.CharField(blank=True, max_length=200)),
                ('nodeLink', models.CharField(blank=True, max_length=200)),
                ('e2eSecInfo', models.CharField(blank=True, max_length=200)),
                ('notificationCongestionPolicy', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='CSEBase',
        ),
        migrations.AddField(
            model_name='app',
            name='creationTime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='app',
            name='expirationTime',
            field=models.DateTimeField(default=datetime.datetime(2099, 11, 16, 0, 0)),
        ),
        migrations.AddField(
            model_name='app',
            name='lastModifiedTime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='container',
            name='creationTime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='container',
            name='expirationTime',
            field=models.DateTimeField(default=datetime.datetime(2099, 11, 16, 0, 0)),
        ),
        migrations.AddField(
            model_name='container',
            name='lastModifiedTime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='contentinstance',
            name='creationTime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='contentinstance',
            name='expirationTime',
            field=models.DateTimeField(default=datetime.datetime(2099, 11, 16, 0, 0)),
        ),
        migrations.AddField(
            model_name='contentinstance',
            name='lastModifiedTime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='subscription',
            name='creationTime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='subscription',
            name='expirationTime',
            field=models.DateTimeField(default=datetime.datetime(2099, 11, 16, 0, 0)),
        ),
        migrations.AddField(
            model_name='subscription',
            name='lastModifiedTime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
