# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-08 07:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0005_auto_20161208_0714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='creationTime',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='app',
            name='lastModifiedTime',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='container',
            name='creationTime',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='container',
            name='lastModifiedTime',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='contentinstance',
            name='creationTime',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='contentinstance',
            name='lastModifiedTime',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='cse',
            name='creationTime',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='cse',
            name='lastModifiedTime',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='creationTime',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='lastModifiedTime',
            field=models.DateTimeField(blank=True),
        ),
    ]
