# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-13 08:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0007_auto_20161208_0738'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='test',
            field=models.ManyToManyField(related_name='_app_test_+', to='resources.APP'),
        ),
        migrations.AddField(
            model_name='container',
            name='test',
            field=models.ManyToManyField(related_name='_container_test_+', to='resources.CONTAINER'),
        ),
        migrations.AddField(
            model_name='contentinstance',
            name='test',
            field=models.ManyToManyField(related_name='_contentinstance_test_+', to='resources.CONTENTINSTANCE'),
        ),
        migrations.AddField(
            model_name='cse',
            name='test',
            field=models.ManyToManyField(related_name='_cse_test_+', to='resources.CSE'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='test',
            field=models.ManyToManyField(related_name='_subscription_test_+', to='resources.SUBSCRIPTION'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='eventNotificationCriteria',
            field=models.CharField(default='{"net":[6], "om":[6]}', max_length=100),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='notificationContentType',
            field=models.IntegerField(default=1),
        ),
    ]
