# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-13 08:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0008_auto_20161213_0811'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='app',
            name='test',
        ),
        migrations.RemoveField(
            model_name='container',
            name='test',
        ),
        migrations.RemoveField(
            model_name='contentinstance',
            name='test',
        ),
        migrations.RemoveField(
            model_name='cse',
            name='test',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='test',
        ),
    ]
