# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-14 08:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0010_auto_20161213_0855'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='app',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='app',
            name='object_id',
        ),
    ]
