# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-14 08:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iotdb_link', '0003_auto_20161120_1618'),
        ('resources', '0011_auto_20161214_0802'),
    ]

    operations = [
        migrations.CreateModel(
            name='test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iotdb_link.Device')),
            ],
        ),
    ]
