# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-14 09:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0013_test_test2'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='test3',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='resources.test'),
            preserve_default=False,
        ),
    ]
