# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-14 09:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0014_test_test3'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='test1',
        ),
    ]
